### ISSUE TITLE
Address the exception when user is beyond API rate limit

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/initiative#3]
The possible solutions might be to catch such an occurrence and then show a modal to the user stating that they would not be able to use the site for sometime and need to come back later when their IP has gone below the limit.

**Comment by s-katte** [comment]
Hey, @t0xic0der assign me this, I will do it.

**Comment by gridhead** [comment]
Cool. There you go.

Happy Hacktoberfest. 🥳
