### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/initiative#4]
In the spirit of getting more contributors for the project, the above documents would be appreciated.

**Comment by tripathyprateek** [comment]
I will take this up and make a generic CONTRIBUTING.md file across most projects.

**Comment by gridhead** [comment]
Sure thing. Assigning this to you.

**Comment by alkatrivedi** [comment]
Just gone through CONTRIBUTION.md can I add something more to it to make it more understable for the contributors?

**Comment by gridhead** [comment]
I am afraid that there is no such file in the repository.

**Comment by alkatrivedi** [comment]
It is there. Right?

**Comment by gridhead** [comment]
You must be referring to CONTRIBUTING.md.

**Comment by alkatrivedi** [comment]
Yes!

**Comment by gridhead** [comment]
The CONTRIBUTING.md looks good to me. I do not think there are any more changes required to it. But if you still believe that there are changes needed, please create a new issue stating the changes that you would want to make. 

I would be closing this one as @tripathyprateek has seemingly done a good job with his PR.
